### ISSUE TITLE
500 error after login with editor role

### ISSUE THREAD

**Issue by bjko** [flutchman/eZMigrationUiBundle#1]
after login to backend with an editor (role) the platform throws a 500 error

php.CRITICAL: Call to a member function addChild() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function addChild() on null at /project-root/vendor/flutchman/ez-migration-ui-bundle/src/EventListener/MenuListener.php:41)"} []

**Comment by homarx** [comment]
#2

**Comment by flutchman** [comment]
Hello,

Thank you for your interest in my project :)
I'll try to look at it soon !

**Comment by flutchman** [comment]
Merged in 0.2.1, thanks :)
